### ISSUE TITLE
Stone Crafting Table does not rotate/ has no orientation

### ISSUE THREAD

**Issue by CreepyCre** [DoctorFTB/Stone-Block-Utilities#11]
Stone Crafting Tables can only be placed in one orientation

How to recreate:
1. Place Stone Crafting Table
2. Put any item in top-middle Stone Crafting Table slot
3. check which direction the item points in outside the interface, it will be south

It's more of a request than a bug report, I still hope you implement this.

**Comment by DoctorFTB** [comment]
Stone Crafting Table work like Vanilla Crafting Table.
Vanilla Crafting Table not have orientation, by logic - I not add orientation to Stone variant.
~
But if players want - I can make that.

**Comment by DoctorFTB** [comment]
Try 2.01.1 version.

**Comment by DoctorFTB** [comment]
@CreepyCre

**Comment by DoctorFTB** [comment]
Closed. Author issue ignore.
