### ISSUE TITLE
SBUTransformer.java take 80% of cpu cycle on server.

### ISSUE THREAD

**Issue by demethan** [DoctorFTB/Stone-Block-Utilities#5]
From what our local guru tells me, this function is taking a very long time to run. We have multiple players (8) on the server and the tps is 10.  tick profiler is not flagging any lag with entities.  Is there something we can disable to fix the slow execution of this function.

**Comment by demethan** [comment]
![image](https://user-images.githubusercontent.com/5810363/43998056-9d028c46-9dba-11e8-9c39-f7ea288f874b.png)

**Comment by DoctorFTB** [comment]
2.0.10 version have config option to disable custom spawn position getter & set to vanilla.
(by default - disable_asm = false)

**Comment by RandomLibrarian** [comment]
ohhh so thats what happened. I wondered why my server got laggy all of a sudden.
