### ISSUE TITLE
[Request] Underground Biom Constructs support

### ISSUE THREAD

**Issue by ghost** [DoctorFTB/Stone-Block-Utilities#8]
I wanted to add UBC to make the underworld more colorful, but there's no config to get pebbles from the stone.

The stone is undergroundbiomes:igneous_stone, sedimentary_stone, and metamorphic_stone meta 0-7 ea. The cobble is igneous_cobble, etc. metas 0-7 ea.

Edit: There's no sedimentary_cobble.

**Comment by DoctorFTB** [comment]
Try 2.0.12 version.

**Comment by DoctorFTB** [comment]
@scribbler957

**Comment by DoctorFTB** [comment]
Closed. Author issue ignore.
