### ISSUE TITLE
Stone crafting table breaks faster with axe, usable as furnace fuel

### ISSUE THREAD

**Issue by maadneet** [DoctorFTB/Stone-Block-Utilities#9]
The stone crafting table seems to act like wood in a number of ways, including breaking faster when using an axe (not a pickaxe) and is usable as a fuel in furnaces. I expected the table to work more like stone does.

**Comment by DoctorFTB** [comment]
The table is supposed to work like an normal crafting table regarding breaking speed and tool requirement. Regarding table working as fuel has been removed in version 2.0.12.
